In [64]:
import praw
import datetime as dt
reddit=praw.Reddit(client_id='IyPUeeAEBYdOlg',client_secret='-Lg3bItpdXi_DgC-psPy1Lna2sk',user_agent='Reddit WebScrapping')

In [65]:
gilded_subreddit = reddit.subreddit('news').gilded(limit=10)
for post in gilded_subreddit:
    print(post)

f3sutxk
f3sr8nz
f3s4090
f3q71dj
f39678x
f3r4ura
dhv791
f3qspag
f3pt48f
f3ryndo

In [66]:
top_subreddit = reddit.subreddit('news').top(limit=10)
for post in top_subreddit:
    print(post.title)

Blizzard Employees Staged a Walkout After the Company Banned a Gamer for Pro-Hong Kong Views
Scientist Stephen Hawking has died aged 76
F.C.C. Announces Plan to Repeal Net Neutrality
Jeffrey Epstein, accused sex trafficker, dies by suicide: Officials
Report: Stan Lee dead at 95 - Story
Arizona Senator John McCain has passed away at the age of 81
Apple admits it slows older iPhones, confirming Geekbench report
Net Neutrality Overturned
Former President George H.W. Bush Dies at 94
Japanese firm gives non-smokers extra six days holiday to compensate for cigarette break

In [67]:
for submission in subreddit.top(limit=1):
    print(submission.title, submission.id)

This is pretty much the biggest red-alert towards legal nootropics in the US. 8r7ipn

In [68]:
import pandas as pd
posts = []
all_subreddit = reddit.subreddit('all')
for post in all_subreddit.top(limit=10):
    posts.append([post.title, post.score, post.id, post.subreddit, post.url, post.num_comments, post.selftext, post.created])
posts = pd.DataFrame(posts,columns=['title', 'score', 'id', 'subreddit', 'url', 'num_comments', 'selftext', 'created'])
def get_date(created):
    return dt.datetime.fromtimestamp(created)
_timestamp = posts["created"].apply(get_date)
posts = posts.assign(timestamp = _timestamp)
posts

,title,score,id,subreddit,url,num_comments,selftext,created,timestamp
0,Guardians of the Front Page,283490,5gn8ru,funny,http://i.imgur.com/OOFRJvr.gifv,5002,,1.480988e+09,2016-12-06 07:11:14
1,"Thanks, Obama.",230832,5bx4bx,pics,https://i.reddituploads.com/58986555f545487c9d...,6109,,1.478680e+09,2016-11-09 13:57:25
2,"This is Shelia Fredrick, a flight attendant. S...",222807,5sfexx,pics,https://i.reddituploads.com/d1e77b5c62694624ba...,4365,,1.486430e+09,2017-02-07 06:36:40
3,1 dad reflex 2 children,204182,5jrlw1,gifs,http://i.imgur.com/Rum0zSz.gifv,5660,,1.482455e+09,2016-12-23 06:27:35
4,Should have been Bernie,163300,5by1wy,pics,https://i.sli.mg/mwl3jS.jpg,8716,,1.478691e+09,2016-11-09 16:57:38
5,2.6 terabyte leak of Panamanian shell company ...,154762,4d75i7,worldnews,http://panamapapers.sueddeutsche.de/articles/5...,12209,,1.459735e+09,2016-04-04 07:31:46
6,Don't forget about this,157904,5pqxdk,pics,http://i.imgur.com/7aGdxhe.jpg,5311,,1.485228e+09,2017-01-24 08:45:17
7,Due to all the health hazards surrounding the ...,141603,4vq7rj,funny,http://i.imgur.com/FApqk3D.jpg,2167,,1.470133e+09,2016-08-02 15:46:13
8,Leo gets the Oscar!,141539,488gjl,movies,https://www.reddit.com/r/movies/comments/488gj...,14950,,1.456751e+09,2016-02-29 18:25:52
9,"If I get 100 upvotes, I'll buy everyone who up...",138604,5ac0p2,pokemon,https://www.reddit.com/r/pokemon/comments/5ac0...,80086,I'm rich and bored. Make me proud Reddit! \n\n...,1.477947e+09,2016-11-01 02:17:38

In [78]:
# # submission.comments.replace_more(limit=0)
# # for comment in submission.comments.list():
# #     print(comment.replies)

# import praw
# reddit=praw.Reddit(client_id='IyPUeeAEBYdOlg',client_secret='-Lg3bItpdXi_DgC-psPy1Lna2sk',user_agent='Reddit WebScrapping')
# comment = reddit.get_info(thing_id = "t1_cbthe8d")
# print(type(comment), comment)
# print(comment.replies)

In [84]:

comments=[]
submission = reddit.submission(id="dhs7eh")
submission.comments.replace_more(limit=0)
for comment in submission.comments.list():
    comments.append([comment.score, comment.id, comment.subreddit,comment.created, comment.ups, comment.downs,comment.parent_id,comment.replies])
comments = pd.DataFrame(comments,columns=['score', 'id', 'subreddit', 'created', 'ups', 'downs','parent_id','replies'])
def get_date(created):
    return dt.datetime.fromtimestamp(created)
_timestamp = comments["created"].apply(get_date)
comments = comments.assign(timestamp = _timestamp)
comments

TypeError: 'Comment' object is not subscriptable

In [91]:
comments.head(10)

,score,id,subreddit,created,ups,downs,parent_id,replies,timestamp
0,58,f3q2fjn,television,1.571097e+09,58,0,t3_dhs7eh,(f3q3wf6),2019-10-15 05:27:05
1,54,f3q2hmy,television,1.571097e+09,54,0,t3_dhs7eh,(f3q47ec),2019-10-15 05:27:29
2,71,f3q0mki,television,1.571097e+09,71,0,t3_dhs7eh,"(f3q25lw, f3q3ti4, f3q7142, f3qe3at, f3qiz5m)",2019-10-15 05:13:59
3,32,f3q38hd,television,1.571098e+09,32,0,t3_dhs7eh,(f3q4qgy),2019-10-15 05:33:02
4,23,f3q41hh,television,1.571098e+09,23,0,t3_dhs7eh,(f3q5tec),2019-10-15 05:38:48
5,23,f3q4wx9,television,1.571098e+09,23,0,t3_dhs7eh,(f3q779x),2019-10-15 05:44:41
6,43,f3q4an0,television,1.571098e+09,43,0,t3_dhs7eh,(f3q69ca),2019-10-15 05:40:32
7,22,f3q44fw,television,1.571098e+09,22,0,t3_dhs7eh,(f3q616p),2019-10-15 05:39:23
8,18,f3q3vs2,television,1.571098e+09,18,0,t3_dhs7eh,(f3q5kcy),2019-10-15 05:37:42
9,15,f3q35fy,television,1.571098e+09,15,0,t3_dhs7eh,(f3q4nhh),2019-10-15 05:32:23

In [86]:
comments[comments['id'] == 'f3q3wf6']

,score,id,subreddit,created,ups,downs,parent_id,replies,timestamp
175,86,f3q3wf6,television,1.571098e+09,86,0,t1_f3q2fjn,"(f3qdo4d, f3qsrzv, f3rf0tw, f3qpucz, f3th48j)",2019-10-15 05:37:49

In [90]:
max(comments['downs'])

0

In [92]:
comments[comments['id'] == 'f3qdo4d']

,score,id,subreddit,created,ups,downs,parent_id,replies,timestamp
318,15,f3qdo4d,television,1.571102e+09,15,0,t1_f3q3wf6,(f3qg0fn),2019-10-15 06:43:39